config/routes.rb
Grid168::Application.routes.draw do

  get 'zoho/getContacts' => 'zoho#getContacts'

	resources :outlets do
		resources :offers
	end

	resources :offers do
		resources :notes
	end

	resources :programmers

	devise_for :users

  resources :users

	root :to => 'offers#index'

	get 'offers/:id/preview' => 'offers#preview'

  post 'offers/:id/sendWorksheet' => 'offers#sendWorksheet'

  post 'offers/:id/setClosedWon' => 'offers#setClosedWon'

  post 'offers/:id/setClosedLost' => 'offers#setClosedLost'

  get 'zoho/export_potential' => 'zoho#export_potential'

  get '/getDRTV' => 'offers#getDRTV'

  get '/offers/:id/reassign' => 'offers#reassign'
  post '/offers/:id/reassign' => 'offers#reassign'

  %w( 404 422 500 ).each do |code|
    get code, :to => 'errors#show', :code => code
  end

end

app/models/programmer.rb
# == Schema Information
#
# Table name: programmers
#
#  id          :integer(4)      not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#  user_id     :integer(4)
#  first_name  :string(255)
#  last_name   :string(255)
#  email       :string(255)
#  phone       :string(255)
#

class Programmer < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :offers

	validates :name, presence: true

	attr_accessible :first_name, :last_name, :description, :name, :email, :phone, :website, :programmerType

	def won
		self.offers.where(:status => 'Closed Won').length
	end

	def lost
		self.offers.where(:status => 'Closed Lost').length
	end
end

app/controllers/programmers_controller.rb
class ProgrammersController < ApplicationController
	before_filter :authenticate_user!

	# GET /programmers
	# GET /programmers.json
	def index
		@programmers = Programmer.all
		@offers = Offer.all

		respond_to do |format|
			format.html # index.html.erb
		end
	end

	# GET /programmers/1
	# GET /programmers/1.json
	# noinspection Rails3Deprecated
	def show
		@programmer = Programmer.find(params[:id])
    @offers = @programmer.offers

		respond_to do |format|
			format.html # show.html.erb
		end
	end

	# GET /programmers/new
	# GET /programmers/new.json
	def new
		@programmer = Programmer.new
		@back_url = params[:back_url]

		respond_to do |format|
			format.html # new.html.erb
		end
	end

	# GET /programmers/1/edit
	# noinspection Rails3Deprecated
	def edit
		@programmer = Programmer.find(params[:id])
		@back_url = params[:back_url]
	end

	# POST /programmers
	# POST /programmers.json
	def create
		@programmer = current_user.programmers.new(params[:programmer])

		respond_to do |format|
			if @programmer.save
				path = params[:back_url] || @programmer
				format.html { redirect_to path, notice: 'Programmer was successfully created.' }
			else
				format.html { render :action => 'new' }
			end
		end
	end

	# PUT /programmers/1
	# PUT /programmers/1.json
	# noinspection Rails3Deprecated
	def update
		@programmer = Programmer.find(params[:id])

		respond_to do |format|
			if @programmer.update_attributes(params[:programmer])
				path = params[:back_url] || @programmer
				format.html { redirect_to path, :notice => 'Programmer was successfully updated.' }
			else
				format.html { render :action => 'edit' }
			end
		end
	end

	# DELETE /programmers/1
	# DELETE /programmers/1.json
	# noinspection Rails3Deprecated
	def destroy
		@programmer = Programmer.find(params[:id])
		@programmer.delete

		respond_to do |format|
			format.html { redirect_to programmers_url }
		end
	end
end

app/helpers/programmers_helper.rb
module ProgrammersHelper
	
end

app/views/programmers/_form.html.erb
<%= form_for @programmer, :html => {:class => 'form-horizontal group-border stripped'} do |f| %>
    <% if @programmer.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@programmer.errors.count, "error") %> prohibited this programmer from being saved:</h2>
          <ul>
            <% @programmer.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="form-group">
      <%= f.label :company_name, :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10"><%= f.text_field :name, :class => 'form-control' %></div>
    </div>
    <div class="form-group">
      <%= f.label :first_name, :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10"><%= f.text_field :first_name, :class => 'form-control' %></div>
    </div>
    <div class="form-group">
      <%= f.label :last_name, :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10"><%= f.text_field :last_name, :class => 'form-control' %></div>
    </div>
    <div class="form-group">
      <%= f.label :email, :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10"><%= f.email_field :email, :class => 'form-control' %></div>
    </div>
    <div class="form-group">
      <%= f.label :website, :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10"><%= f.text_field :website, :class => 'form-control' %></div>
    </div>
    <div class="form-group">
      <%= f.label :phone, :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10"><%= f.text_field :phone, :class => 'form-control' %></div>
    </div>
    <div class="form-group">
      <%= f.label :description, 'Description', :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10"><%= f.text_area :description, :class => 'form-control' %></div>
    </div>
    <div class="form-group">
      <%= f.label :type, :class => 'col-lg-2 col-md-3 control-label' %>
      <div class="col-lg-10 col-md-9">
        <%= select('programmer', 'programmerType', ['General', 'DRTV', 'Home Shopping', 'Paid Religion', 'Programmer', 'LifehacksDRTV']) %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-4 col-sm-offset-2">
        <%= button_tag(type: 'submit', class: 'btn btn-primary') do %>
            <i class="fa fa-save"></i> Save
        <% end %>
        <%= link_to programmers_path, :method => :get, :class => 'btn cancel' do %>
            <i class="fa fa-remove"></i> Cancel
        <% end %>
      </div>
    <% end %>
</div>

app/views/programmers/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="page-title">
      <h1>Edit Programmer
        <small></small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-home"></i></a></li>
        <li>Programmers</li>
        <li class="active">Edit Programmer</li>
      </ol>
    </div>
  </div>
</div>
<div class="row">
  <div class="panel panel-default margin-b-30">
    <div class="panel-heading">
      <h4 class="panel-title">Edit selected Programmer</h4>
    </div>
    <div class="panel-body">
      <%= render :partial => 'programmers/form' %>
    </div>
  </div>
</div>
<%= render :partial => 'layouts/zoho_contact_search' %>

app/views/programmers/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="page-title">
      <h1><%= current_user.admin? ? 'All Programmers' : 'My Programmers' %>
        <small></small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-home"></i></a></li>
        <li>View Programmers</li>
        <li class="active"><%= current_user.admin? ? 'All Programmers' : 'My Programmers' %></li>
      </ol>
    </div>
  </div>
</div><!-- end .page title-->
<div class="row">
  <div class="col-md-6">
    <div class="navButtons">
      <%= button_to 'New Media Outlet', new_outlet_path, {:class => 'btn btn-primary', :method => :get} %>
      <%= button_to 'New Programmer', new_programmer_path, {:class => 'btn', :method => :get} %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="filterBox">
      <input type="text" class="form-control input-md filterText" placeholder="Filter" type="search">
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default margin-b-30">
      <div class="panel-heading">
        <h4 class="panel-title">Programmers</h4>
        <!--<div class="panel-actions">-->
          <!--<a href="#" class="panel-action panel-action-toggle" data-panel-toggle></a>-->
          <!--<a href="#" class="panel-action panel-action-dismiss" data-panel-dismiss></a>-->
        <!--</div>-->
      </div>
      <div class="panel-body">
        <div class="table-responsive">
          <table id="basic-datatables" class="table table-striped sortable filterable">
            <thead>
              <tr>
                <th>Company Name</th>
                <th>Current</th>
                <th>Lost</th>
                <th>Won</th>
                <th>Last Offer Date</th>
                <th>Email</th>
                <th>URL</th>
								<th>Updated</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
            <% @programmers.each do |programmer| %>
                <tr>
                  <td><%= programmer.name %></td>
                  <td><%= programmer.offers.length %></td>
                  <td><%= programmer.lost %></td>
                  <td><%= programmer.won %></td>
                  <td><%= programmer.offers.length > 0 ? programmer.offers.last.created_at.strftime('%m/%d/%Y') : 'No Offers' %></td>
                  <td><%= mail_to programmer.email %></td>
                  <td><a href="<%= programmer.website.start_with?('http://') ? programmer.website : 'http://' + programmer.website %>" target="_new"><%= programmer.website %></a></td>
                  <td><%= programmer.updated_at.strftime '%m/%d/%Y' %></td>
                  <td>
                    <div class="btn-group">
                      <button type="button" class="btn btn-primary droptown-toggle" data-toggle="dropdown">
                        Actions&nbsp;<span class="caret"></span></button>
                      <ul class="dropdown-menu">
                        <li><a href="<%= url_for programmer_path(programmer.id) %>">Display</a></li>
                        <li><a href="<%= url_for edit_programmer_path(programmer.id) %>">Edit</a></li>
                        <li><%= link_to 'Delete', programmer_path(programmer.id), :method => :delete, :data => {:confirm => 'Are you sure?'} %></li>
                      </ul>
                    </div>
                  </td>
                </tr>
			      <% end %><!-- end programmer -->
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/programmers/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="page-title">
      <h1>New Programmer
        <small></small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-home"></i></a></li>
        <li>Programmers</li>
        <li class="active">New Programmer</li>
      </ol>
    </div>
  </div>
</div>
<div class="row">
  <div class="panel panel-default margin-b-30">
    <div class="panel-heading">
      <h4 class="panel-title">Add a new Programmer</h4>
    </div>
    <div class="panel-body">
      <%= render :partial => 'programmers/form' %>
      </div>
    </div>
</div>
<%= render :partial => 'layouts/zoho_contact_search' %>

app/views/programmers/show.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="page-title">
      <h1><%= @programmer.name %>
        <small></small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-home"></i></a></li>
        <li>Programmers</li>
        <li class="active"><%= @programmer.name %></li>
      </ol>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <div class="navButtons">
      <%= button_to 'Edit', edit_programmer_path(@programmer), :class => 'btn btn-primary', :method => :get %>
      <%= button_to 'Delete', @programmer, :confirm => 'Are you sure?', :method => :delete, :class => 'btn' %>
      <%= link_to new_programmer_path do -%>
          <button type="button" class="btn btn-default">New Programmer</button>
      <% end %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="filterBox">
      <input type="text" class="form-control input-md filterText" placeholder="Filter" type="search">
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default margin-b-30 ">
      <!-- Start .panel -->
      <div class="panel-heading">
        <h4 class="panel-title"> Programmer Details</h4>
      </div>
      <div class="panel-body">
        <p><strong>Name </strong><%= @programmer.name %></p>
        <p><strong>Type </strong><%= @programmer.programmerType %></p>
        <p><strong>First Name </strong><%= @programmer.first_name %></p>
        <p><strong>Last Name </strong><%= @programmer.last_name %></p>
        <p><strong>Updated At </strong><%= @programmer.updated_at.strftime '%m/%d/%Y' %></p>
        <p><strong>Created At </strong><%= @programmer.created_at.strftime '%m/%d/%Y' %></p>
        <p><strong>Email </strong><%= mail_to @programmer.email %></p>
        <p><strong>Phone </strong><%= @programmer.phone %></p>

        <p><strong>Website </strong><a href="<%= @programmer.website.start_with?('http://') ? @programmer.website : 'http://' + @programmer.website %>" target="_new"><%= @programmer.website %></a></p>
        <div class="panel panel-info">
          <div class="panel-heading">Description</div>
          <div class="panel-body"><%= @programmer.description %></div>
        </div>
      </div><!--end .col-->
    </div>
    <div class="panel panel-default margin-b-30">
      <!-- Start .panel -->
      <div class="panel-heading">
        <h4 class="panel-title">Offers</h4>
        <div class="panel-actions">
          <a class="panel-action panel-action-toggle" data-panel-toggle="" href="#"></a>
          <a class="panel-action panel-action-dismiss" data-panel-dismiss="" href="#"></a>
        </div>
      </div>
      <div class="panel-body">
        <table class="table table-striped sortable filterable">
          <thead>
          <tr>
            <th>Outlet</th>
            <th>DMA</th>
            <th>Yearly</th>
            <th>Offer Amount</th>
            <th>Weekly Hours</th>
            <th>Media Type</th>
            <th>Status</th>
            <th>Notes</th>
            <th>Created At</th>
            <th>Status</th>
            <th>User</th>
            <th>Actions</th>
          </tr>
          </thead>
          <tbody>
          <% @offers.each do |offer| %>
              <tr>
                <td><%= offer.outlet.name %></td>
                <td><%= offer.outlet.dma.name %></td>
                <td><%= number_to_currency offer.yearly_offer %></td>
                <td><%= number_to_currency offer.dollar_amount %></td>
                <td><%= offer.weekly_hours %></td>
                <td><%= offer.outlet.outlet_type.name %></td>
                <td><%= offer.status %></td>
                <td><%= offer.internalNotes[0, 99] rescue '' %></td>
                <td><%= offer.created_at.strftime '%m/%d/%y' %></td>
                <td><%= offer.status %></td>
                <td><%= offer.user.first_name %></td>
                <td>
                  <div class="btn-group">
                    <button type="button" class="btn btn-primary droptown-toggle" data-toggle="dropdown">
                      Actions&nbsp;<span class="caret"></span></button>
                    <ul class="dropdown-menu">
                      <li><a href="<%= url_for offer_path(offer.id) %>">Display</a></li>
                      <li><a href="<%= url_for edit_offer_path(offer.id) %>">Edit</a></li>
                      <li><a href="<%= url_for offer_path(offer.id) %>/preview">Preview Email</a></li>
                      <% unless offer.zoho_exported %>
                          <li><%= link_to 'Export to Zoho', zoho_export_potential_path + '?id=' + offer.id.to_s, :data => {:confirm => 'Are you sure you want to export this offer to Zoho?'} %></li>
                      <% end %>
                      <li><%= link_to 'Closed Won', offer_path(offer.id) + '/setClosedWon', :method => :post, :data => {:confirm => 'Are you sure?'} %></li>
                      <li><%= link_to 'Closed Lost', offer_path(offer.id) + '/setClosedLost', :method => :post, :data => {:confirm => 'Are you sure?'} %></li>
                      <li><%= link_to 'Delete', offer_path(offer.id), :method => :delete, :data => {:confirm => 'Are you sure?'} %></li>
                    </ul>
                  </div>
                </td>
              </tr>
              <% end %><!-- end programmer -->
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>