config/routes.rb
Grid168::Application.routes.draw do

  get 'zoho/getContacts' => 'zoho#getContacts'

	resources :outlets do
		resources :offers
	end

	resources :offers do
		resources :notes
	end

	resources :programmers

	devise_for :users

  resources :users

	root :to => 'offers#index'

	get 'offers/:id/preview' => 'offers#preview'

  post 'offers/:id/sendWorksheet' => 'offers#sendWorksheet'

  post 'offers/:id/setClosedWon' => 'offers#setClosedWon'

  post 'offers/:id/setClosedLost' => 'offers#setClosedLost'

  get 'zoho/export_potential' => 'zoho#export_potential'

  get '/getDRTV' => 'offers#getDRTV'

  get '/offers/:id/reassign' => 'offers#reassign'
  post '/offers/:id/reassign' => 'offers#reassign'

  %w( 404 422 500 ).each do |code|
    get code, :to => 'errors#show', :code => code
  end

end

app/models/outlet.rb
# == Schema Information
#
# Table name: outlets
#
#  id           :integer(4)      not null, primary key
#  name         :string(255)     not null
#  description  :string(255)
#  subs         :integer(4)      not null
#  dma_id       :integer(4)      not null
#  user_id      :integer(4)      not null
#  created_at   :datetime
#  updated_at   :datetime
#  outlet_type  :integer(4)      default(0), not null
#  first_name   :string(255)
#  last_name    :string(255)
#  phone_number :string(255)
#

class Outlet < ActiveRecord::Base
	belongs_to :user
	belongs_to :dma
  belongs_to :outlet_type
	with_options :dependent => :destroy do |o|
		o.has_many :offers
  end

  after_initialize :set_defaults, :unless => :persisted?


  attr_accessible :name, :first_name, :last_name, :phone_number, :description, :subs, :dma_id, :user_id,
                  :outlet_type_id, :time_zone, :programming, :over_air, :total_homes, :email, :website, :contour_map, :title, :zoho_contact_id

	validates :name, :first_name, :last_name, :phone_number, :dma_id, :subs, :outlet_type, :presence => true

	validates :name, uniqueness: { case_sensitive: false, message: 'This outlet name already exists' }

  # Return the number of offers of this outlet with status "Closed Won"
  def won
    self.offers.where(:status => 'Closed Won').length
  end

  # Return the number of offers of this outlet with status "Closed Lost"
  def lost
    self.offers.where(:status => 'Closed Lost').length
  end

	def fullname
		self.first_name + ' ' + self.last_name
  end

  private

  def set_defaults
    self.website ||= ''
  end

end

app/models/outlet_type.rb
class OutletType < ActiveRecord::Base
  has_many :outlets

  attr_accessible :name
end

app/controllers/outlets_controller.rb
class OutletsController < ApplicationController
	before_action :sanitizeParameters, :only => [:create, :update]


	def index
		@outlets = Outlet.all
	end #end index action

	def show
		@outlet = Outlet.find(params[:id])
		@user_id = @outlet.user_id

	end #end show action

	def new
		@types = OutletType.all
		@outlet = current_user.outlets.build
	end #end new action

	def create
		@outlet = Outlet.new(params[:outlet])
		respond_to do |format|
			if @outlet.save
				format.html { redirect_to outlets_path, :notice => 'Outlet was successfully created.'}
			else
				format.html { render :action => :new }
			end
		end #end respond_to
	end #end create action

	def edit
		@outlet = Outlet.find(params[:id])
		@offer_id = params[:offer_id] || 0
	end #end edit action

	def update
		@outlet = Outlet.find(params[:id])

		respond_to do |format|
      if @outlet.update(params[:outlet])
				format.html { redirect_to @outlet, notice: "Media Outlet #{@outlet.name} was successfully updated." }
      else
        format.html { render :edit, error: @outlet.errors }
      end
    end
	end #end update action

	def destroy
		@outlet =Outlet.find(params[:id])
		@outlet.destroy

		respond_to do |format|
			format.html { redirect_to outlets_path }
		end #end respond_to
	end #end destroy action

end #end Outlets controller

app/helpers/outlets_helper.rb
module OutletsHelper

	# def outlet_types
	# 	[
	# 		["Broadcast", 1],
	# 		["Cable system", 2],
	# 		["Network", 3],
	# 		["Sub channel", 4]
	# 	]
	# end #end outlet_types

	def get_type(index)
		result = ""
		outlet_types.each do |k, v|
			if v == index
				result = k
				break
			end
		end

		result
	end #end get_type

	def convert2Decimal(number)
		num, dec = number.split(".")
		if dec.length < 2
			dec += "0"
		end
		num + "." + dec
	end #end convert2Decimal
end

app/views/outlets/_form.html.erb
<%= form_for @outlet, :html => {:class => 'form-horizontal group-border stripped'} do |f| %>
    <% if @outlet.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@outlet.errors.count, 'error') %> prohibited this outlet from being saved:</h2>
          <ul>
            <% @outlet.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="form-group">
      <%= f.label :company_name, 'Name', :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10"><%= f.text_field :name, :class => 'form-control' %></div>
    </div>
    <div class="form-group">
      <%= f.label :first_name, 'First Name', :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10"><%= f.text_field :first_name, :class => 'form-control' %></div>
    </div>
    <div class="form-group">
      <%= f.label :last_name, 'Last Name', :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10"><%= f.text_field :last_name, :class => 'form-control' %></div>
    </div>

    <div class="form-group">
      <%= f.label :title, 'Title', :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10"><%= f.text_field :title, :class => 'form-control' %></div>
    </div>

    <div class="form-group">
      <%= f.label :phone_number, 'Phone', :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10"><%= f.text_field :phone_number, :class => 'form-control', :id => 'outlet_phone' %></div>
    </div>

    <div class="form-group">
      <%= f.label :email, 'Email', :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10"><%= f.email_field :email, :class => 'form-control' %></div>
    </div>

    <div class="form-group">
      <%= f.label :website, 'Website', :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10"><%= f.text_field :website, :class => 'form-control' %></div>
    </div>

    <div class="form-group">
      <%= f.label :contour_map, 'Contour Map URL', :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10"><%= f.text_field :contour_map, :class => 'form-control', :id => 'contour_map' %></div>
    </div>

    <div class="form-group">
      <%= f.label :zoho_contact_id, 'Zoho Contact ID', :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10"><%= f.text_field :zoho_contact_id, :class => 'form-control', :id => 'zoho_contact_id' %></div>
    </div>

    <div class="form-group">
      <%= f.label :programming, :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10"><%= f.text_field :programming, :class => 'form-control' %></div>
    </div>

    <div class="form-group">
      <%= f.label :subs, 'MVPD Subscribers', :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10"><%= f.text_field :subs, :class => 'form-control delimited' %></div>
    </div>

    <div class="form-group">
      <%= f.label :over_air, 'Over the Air Homes', :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10"><%= f.text_field :over_air, :class => 'form-control delimited' %></div>
    </div>

    <div class="form-group">
      <%= f.label :total_homes, 'Total Homes', :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10"><%= f.text_field :total_homes, :class => 'form-control delimited' %></div>
    </div>

    <div class="form-group">
      <%= f.label :dma, "DMA", :class => 'col-lg-2 col-md-3 control-label' %>
      <div class="col-lg-10 col-md-9">
        <%= select("outlet", "dma_id", options_for_select(Dma.order("id DESC").collect { |d| [d.name, d.id] })) %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :type, :class => 'col-lg-2 col-md-3 control-label' %>
      <div class="col-lg-10 col-md-9">
        <%= select("outlet", "outlet_type_id", OutletType.order(:name).collect { |d| [d.name, d.id] }) %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :time_zone, :class => 'col-lg-2 col-md-3 control-label' %>
      <div class="col-lg-10 col-md-9">
        <%= f.select(:time_zone, options_for_select([
          'Atlantic (GMT-04:00)',
          'Eastern (GMT-05:00)',
          'Central (GMT-06:00)',
          'Mountain (GMT-07:00)',
          'Pacific (GMT-08:00)',
          'Alaska (GMT-09:00)',
          'Hawaii-Aleutian Islands (GMT-10:00)',
          'America Samoa (GMT -11:00)',
          'Marshalls Islands (GMT+12:00)',
          'Guam (GMT+10:00)',
          'Palau (GMT+9:00)',
          'Samoa Standard Time'
          ])) %>
        <input type="hidden" id="timeZoneHidden" value="<%= @outlet.time_zone %>" />
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-4 col-sm-offset-2" style="margin-top: 15px;">
        <%= button_tag(type: 'submit', class: "btn btn-primary") do -%>
            <i class="icon-ok icon-white"></i> Save
        <% end %>
        <%= link_to outlets_path, :class => 'btn cancel' do -%>
            <i class="fa fa-remove"></i> Cancel
        <% end %>
      </div>
    </div>

    <%= f.hidden_field(:user_id, :value => current_user.id) %>
<% end %>

app/views/outlets/_outlet.html.erb
<tr>
	<td><%= outlet.name %></td>
	<td><%= outlet.offers.count %></td>
	<td><%= number_with_delimiter outlet.subs %></td>
	<td><%= outlet.dma.name rescue "None" %></td>
	<td><%= outlet.created_at.strftime "%m/%d/%Y" %></td>
	<td>
		<%= link_to "show", outlet_path(outlet) %> |
    <%= link_to "edit", edit_outlet_path(outlet) %> |
		<%= link_to "delete", outlet, :confirm => "Are you sure?", :method => :delete %>
	</td>
</tr>

app/views/outlets/_outlet_show.html.erb
<div id="outlet_info">
  
	<span class="name"><%= outlet.name %></span>
	<span class="dma">DMA:<%= outlet.dma.name rescue "None" %></span>
	<span class="subs"><%= number_with_delimiter outlet.subs %> subscribers</span>

        | <%= link_to "Edit", edit_outlet_path(outlet) %> |
        <%= link_to 'Destroy', outlet_path(outlet), :confirm => 'Are you sure?', :method => :delete %>
</div>

<table id="table_outlet_show" class="tablesorter">
	<thead>
		<tr>
			<th>Programmer</th>
			<th>Dollar amount</th>
			<th>Created at</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		<%= render outlet.offers %>
	</tbody>
</table>

<%= link_to(image_tag("new_offer.png"), new_outlet_offer_path(outlet)) %>

app/views/outlets/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="page-title">
      <h1>Edit Media Outlet
        <small></small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-home"></i></a></li>
        <li>Media Outlets</li>
        <li class="active">New Media Outlet</li>
      </ol>
    </div>
  </div>
</div>
<div class="row">
  <div class="panel panel-default margin-b-30">
    <div class="panel-heading">
      <h4 class="panel-title">Add a new Media Outlet</h4>
    </div>
    <div class="panel-body">
      <%= render :partial => 'outlets/form' %>
    </div>
  </div>
</div>
<%= render :partial => 'layouts/zoho_contact_search' %>

app/views/outlets/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="page-title">
      <% if current_user.admin? %>
          <h1>All Media Outlets</h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-home"></i></a></li>
            <li class="active">All Media Outlets</li>
          </ol>
      <% else %>
          <h1>My Media Outlets</h1>
          <ol class="breadcrumb">
            <li><a href='#'><i class="fa fa-home"></i></a></li>
            <li class="active">My Media Outlets</li>
          </ol>
      <% end %>
    </div>
  </div>
</div><!-- end .page title-->
<div class="row">
  <div class="col-md-6">
    <div class="navButtons">
      <%= button_to 'New Media Outlet', new_outlet_path, {:class => 'btn btn-primary', :method => :get} %>
      <%= button_to 'New Programmer', new_programmer_path, {:class => 'btn', :method => :get} %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="filterBox">
      <input type="text" class="form-control input-md filterText" placeholder="Filter" type="search">
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default margin-b-30">
      <div class="panel-heading">
        <h4 class="panel-title">Outlets</h4>
        <!--<div class="panel-actions">-->
          <!--<a href="#" class="panel-action panel-action-toggle" data-panel-toggle></a>-->
          <!--<a href="#" class="panel-action panel-action-dismiss" data-panel-dismiss></a>-->
        <!--</div>-->
      </div>
      <div class="panel-body">
        <div class="table-responsive">
          <table id="basic-datatables" class="table table-striped sortable filterable">
            <thead>
              <tr>
                <th>Created At</th>
                <th>Name</th>
                <th>Current</th>
                <th>Lost</th>
                <th>Won</th>
                <th>MVPD Subs</th>
                <th>Over Air</th>
                <th>Total Homes</th>
                <th>Market</th>
                <th>Media Type</th>
                <th>User</th>
                <th>&nbsp;</th>
              </tr>
            </thead>
            <tbody>
              <% @outlets.each do |outlet| -%>
                <tr>
                  <td><%= outlet.created_at.strftime '%m/%d/%Y' %></td>
                  <td><%= outlet.name %></td>
                  <td><%= outlet.offers.length %></td>
                  <td><%= outlet.lost %></td>
                  <td><%= outlet.won %></td>
                  <td><%= number_with_delimiter outlet.subs %></td>
                  <td><%= number_with_delimiter outlet.over_air %></td>
                  <td><%= number_with_delimiter outlet.total_homes %></td>
                  <td><%= outlet.dma.name rescue 'None' %></td>
                  <td><%= outlet.outlet_type.name %></td>
                  <td><%= outlet.user.first_name rescue 'None' %></td>
                  <td>
                    <div class="btn-group">
                      <button type="button" class="btn btn-primary droptown-toggle" data-toggle="dropdown">
                        Actions&nbsp;<span class="caret"></span></button>
                      <ul class="dropdown-menu">
                        <li><%= link_to 'New Offer', new_outlet_offer_path(outlet) %></li>
                        <li><%= link_to 'Display', outlet_path(outlet) %></li>
                        <li><%= link_to 'Edit', edit_outlet_path(outlet) %></li>
                        <li><%= link_to 'Delete', outlet_path(outlet), :method => :delete, :data => {:confirm => 'Are you sure?'} %></li>
                      </ul>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/outlets/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="page-title">
      <h1>New Media Outlet
        <small></small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-home"></i></a></li>
        <li>Media Outlets</li>
        <li class="active">New Media Outlet</li>
      </ol>
    </div>
  </div>
</div>
<div class="row">
  <div class="panel panel-default margin-b-30">
    <div class="panel-heading">
      <h4 class="panel-title">Add a new Media Outlet</h4>
    </div>
    <div class="panel-body">
      <%= render :partial => 'outlets/form' %>
    </div>
  </div>
</div>
<%= render :partial => 'layouts/zoho_contact_search' %>

app/views/outlets/show.html.erb
<div class="row">
  <div class="col-sm-12">
      <div class="page-title">
          <h1><%= @outlet.name %> <small></small></h1>
          <ol class="breadcrumb">
              <li>
                  <a href="#"><i class="fa fa-home"></i></a>
              </li>
              <li>Media Outlets</li>
              <li class="active">Show Media Outlet</li>
          </ol>
      </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-6">
    <p><strong>Media Type: </strong><%= @outlet.outlet_type.name %></p>
    <% if @outlet.website %><p><strong>Website:</strong> <a href="<%= @outlet.website.start_with?('http://') ? @outlet.website : 'http://' + @outlet.website %>" target="_new"><%= @outlet.website %></a></p><% end %>
    <% if @outlet.contour_map %><p><strong>Contour Map:</strong>
    <a target="_new" href="<%= @outlet.contour_map %>"><%= @outlet.contour_map %></a></p>
    <% end %>
    <p><strong>Time Zone:</strong> <%= @outlet.time_zone %></p>
  </div>
  <div class="col-sm-6">
    <p><strong>Contact:</strong> <%= @outlet.first_name %> <%= @outlet.last_name %></p>
    <p><strong>Phone:</strong> <%= @outlet.phone_number %></p>
    <p><strong>Email:</strong> <%= mail_to @outlet.email %></p>
  </div>
</div>
<div class="row">
    <div class="col-sm-6 col-md-3 margin-b-30">
        <div class="tile red">
            <div class="tile-title clearfix">
                Total Subscribers <span class="pull-right"></span>
            </div><!--.tile-title-->
            <div class="tile-body clearfix">
                <i class="fa fa-cart-plus"></i>
                <h4 class="pull-right">
                <%= number_with_delimiter @outlet.subs %></h4>
            </div><!--.tile-body-->
            <div class="tile-footer">
                &nbsp;
            </div><!--.tile footer-->
        </div><!-- .tile-->
    </div><!-- .col -->
    <div class="col-sm-6 col-md-3 margin-b-30">
        <div class="tile green">
            <div class="tile-title clearfix">
                Market <span class="pull-right"></span>
            </div><!--.tile-title-->
            <div class="tile-body clearfix">
                <i class="fa fa-credit-card"></i>
                <h4 class="pull-right" style="font-size: large;">
                    <%= @outlet.dma.name %>
                </h4>
            </div><!--.tile-body-->
            <div class="tile-footer">
                &nbsp;
            </div><!--.tile footer-->
        </div><!-- .tile-->
    </div><!--end .col-->
    <div class="col-sm-6 col-md-3 margin-b-30">
        <div class="tile blue">
            <div class="tile-title clearfix">
                OTA Homes <span class="pull-right"></span>
            </div><!--.tile-title-->
            <div class="tile-body clearfix">
                <i class="fa fa-users"></i>
                <h4 class="pull-right"><%= number_with_delimiter @outlet.over_air %></h4>
            </div><!--.tile-body-->
            <div class="tile-footer">
                &nbsp;
            </div><!--.tile footer-->
        </div><!-- .tile-->
    </div><!--end .col-->
    <div class="col-sm-6 col-md-3 margin-b-30">
        <div class="tile purple">
            <div class="tile-title clearfix">
                Total homes <span class="pull-right"></span>
            </div><!--.tile-title-->
            <div class="tile-body clearfix">
                <i class="fa fa-cart-plus"></i>
                <h4 class="pull-right">
                <%= number_with_delimiter @outlet.total_homes %></h4>
            </div><!--.tile-body-->
            <div class="tile-footer">
                &nbsp;
            </div><!--.tile footer-->
        </div><!-- .tile-->
    </div><!--end .col-->
</div>
<div class="row">
  <div class="col-sm-6">
    <div class="navButtons">
      <%= button_to 'Edit', edit_outlet_path(@outlet), :class => 'btn btn-primary', :method => :get %>
      <%= button_to 'Delete', @outlet, :confirm => 'Are you sure?', :method => :delete, :class => 'btn' %>
      <%= button_to 'New Offer', new_outlet_offer_path(@outlet), :class => 'btn', :method => :get %>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="filterBox">
      <input type="text" class="form-control input-md filterText" placeholder="Filter" type="search">
    </div>
  </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default margin-b-30">
            <!-- Start .panel -->
            <div class="panel-heading">
                <h4 class="panel-title">Offers</h4>
                <div class="panel-actions">
                    <a class="panel-action panel-action-toggle"
                    data-panel-toggle="" href="#"></a> <a class=
                    "panel-action panel-action-dismiss" data-panel-dismiss=
                    "" href="#"></a>
                </div>
            </div>
            <div class="panel-body">
                <table class="table table-striped tablesorter filterable">
                    <thead>
                        <tr>
                          <th>Programmer</th>
                          <th>Status</th>
                          <th>Yearly</th>
                          <th>Offer Amount</th>
                          <th>Weekly Hours</th>
                          <th>Programmer Type</th>
                          <th>Created At</th>
                          <th>Notes</th>
                          <th>User</th>
                          <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    <% @outlet.offers.each do |offer| %>
                        <% offer.programmers.each do |programmer| %>
                        <tr>
                            <td><%= programmer.name %></td>
                            <td><%= offer.status %></td>
                            <td><%= number_to_currency offer.yearly_offer %></td>
                            <td><%= number_to_currency offer.dollar_amount %></td>
                            <td><%= offer.weekly_hours %></td>
                            <td><%= programmer.programmerType %></td>
                            <td><%= offer.created_at.strftime("%m/%d/%y") %></td>
                            <td><%= offer.internalNotes rescue ''%></td>
                            <td><%= offer.user.first_name %></td>
                            <td>
                                <div class="btn-group">
                                  <button type="button" class="btn btn-primary droptown-toggle" data-toggle="dropdown">
                                    Actions&nbsp;<span class="caret"></span></button>
                                  <ul class="dropdown-menu">
                                    <li><a href="<%= url_for offer_path(offer.id) %>">Display</a></li>
                                    <li><a href="<%= url_for edit_offer_path(offer.id) %>">Edit</a></li>
                                    <li><a href="<%= url_for offer_path(offer.id) %>/preview">Preview Email</a></li>
                                    <% unless offer.zoho_exported %>
                                        <li><%= link_to 'Export to Zoho', zoho_export_potential_path + '?id=' + offer.id.to_s, :data => {:confirm => 'Are you sure you want to export this offer to Zoho?'} %></li>
                                    <% end %>
                                    <li><%= link_to 'Closed Won', offer_path(offer.id) + '/setClosedWon', :method => :post, :data => {:confirm => 'Are you sure?'} %></li>
                                    <li><%= link_to 'Closed Lost', offer_path(offer.id) + '/setClosedLost', :method => :post, :data => {:confirm => 'Are you sure?'} %></li>
                                    <li><%= link_to 'Delete', offer_path(offer.id), :method => :delete, :data => {:confirm => 'Are you sure?'} %></li>
                                  </ul>
                                </div>
                            </td>
                        </tr><%end %><!-- end programmer -->
                        <%end %><!-- end offer of outlet -->
                    </tbody>
                </table>
            </div>
        </div><!-- End .panel -->
    </div><!--end .col-->
</div>