config/routes.rb
Grid168::Application.routes.draw do

  get 'zoho/getContacts' => 'zoho#getContacts'

	resources :outlets do
		resources :offers
	end

	resources :offers do
		resources :notes
	end

	resources :programmers

	devise_for :users

  resources :users

	root :to => 'offers#index'

	get 'offers/:id/preview' => 'offers#preview'

  post 'offers/:id/sendWorksheet' => 'offers#sendWorksheet'

  post 'offers/:id/setClosedWon' => 'offers#setClosedWon'

  post 'offers/:id/setClosedLost' => 'offers#setClosedLost'

  get 'zoho/export_potential' => 'zoho#export_potential'

  get '/getDRTV' => 'offers#getDRTV'

  get '/offers/:id/reassign' => 'offers#reassign'
  post '/offers/:id/reassign' => 'offers#reassign'

  %w( 404 422 500 ).each do |code|
    get code, :to => 'errors#show', :code => code
  end

end

app/models/offer.rb
# == Schema Information
#
# Table name: offers
#
#  id                :integer(4)      not null, primary key
#  outlet_id         :integer(4)
#  yearly_offer      :float           default(0.0), not null
#  monthly_offer     :float           default(0.0), not null
#  weekly_offer      :float           default(0.0), not null
#  hourly_rate       :float           default(0.0), not null
#  total_hours       :float           default(0.0), not null
#  created_at        :datetime
#  updated_at        :datetime
#  dollar_amount     :float           default(0.0), not null
#  half_hour_clicked :text
#  user_id           :integer(4)
#

class Offer < ActiveRecord::Base
	after_initialize :set_defaults, :unless => :persisted?

	belongs_to :outlet
	has_and_belongs_to_many :programmers
	belongs_to :user
	has_many :notes, :dependent => :destroy

  	attr_accessible :programmer_ids, :yearly_offer, :monthly_offer, :outlet_id, :weekly_hours,
									:monthly_hours, :yearly_hours, :weekly_offer, :hourly_rate, :total_hours,
									:dollar_amount, :user_id, :time_cells, :available_date, :grNotes, :dpNotes,
									:mvpdSubscriberRate, :mvpdOtaSubRate, :halfHourRate, :morningAudience,
									:morningRate, :morningHours, :morningWeeklyRate, :daytimeAudience, :daytimeRate,
									:daytimeHours, :daytimeWeeklyRate, :eveningNewsAudience, :eveningNewsRate,
									:eveningNewsHours, :eveningNewsWeeklyRate, :localPrimeTimeAudience, :localPrimeTimeRate,
									:localPrimeTimeHours, :localPrimeTimeWeeklyRate, :nationalPrimeTimeAudience,
									:nationalPrimeTimeRate, :nationalPrimeTimeHours, :nationalPrimeTimeWeeklyRate,
									:lateNewsAudience, :lateNewsRate, :lateNewsHours, :lateNewsWeeklyRate, :lateNightAudience,
									:lateNightRate, :lateNightHours, :lateNightWeeklyRate, :overnightsAudience, :overnightsRate,
									:overnightsHours, :overnightsWeeklyRate, :runningAudienceTotal, :runningHoursTotal, :runningWeeklyRateTotal,
									:disclaimer,
									:internalNotes,
									:status,
									:programming

  	validates :dollar_amount, :presence => true,
								numericality: { greater_than: 0 }

	validates :total_hours, numericality: {
      greater_than: 0,
      message: 'You must select half-hour and calculate.'
								}

	validates :programmer_ids, :hourly_rate, :monthly_offer, :weekly_offer, :yearly_offer,
						:dollar_amount, :total_hours, :user_id, presence: true

	# list all programmers's name of this offer and parse to array
	def list_programmer_names
		self.programmers.select(:name).map{|x| x.name}
	end

	private

	def set_defaults
		self.disclaimer ||= "This worksheet is neither a bid nor an offer made on behalf of a programming supplier or on behalf of any other third-party.
    Across Platforms, Inc. is not acting as an agent for any third-party. This worksheet is merely an example of the terms that might be available, based upon the information mentioned in the worksheet, and Across Platforms' considerable expertise in the television industry.
    It is not a representation that these terms are available. With your permission, Across Platforms may submit this worksheet to various programming suppliers whose identities will be determined according to Across Platforms' sole and exclusive discretion.
    In the event there are any further negotiations between you and any programming supplier contacted by Across Platforms, then Across Platforms will be acting as an agent for the programming supplier, and will be paid a commission by the programming supplier if the negotiations result in a binding contract.
    "

    self.grNotes ||= 'Annual Rate for MVPD and OTA - Per OTA home and MVPD subscriber annual cost\nMVPD Subscriber Rate - Per subscriber annual cost (not including OTA)
    OTA Home Rate - Per OTA home annual cost (not including MVPD)'

    self.dpNotes ||= 'Estimated percentage of weekly viewing is a composite of publicly reported viewing trends across all television channels, and networks, based on live time of day viewing.'
    self.status ||= 'Current'

  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer(4)      not null, primary key
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(255)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer(4)      default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  admin                  :boolean(1)      default(FALSE)
#  phone                  :string(255)
#  title                  :string(255)
#  first_name             :string(255)
#  last_name              :string(255)
#

class User < ActiveRecord::Base
	with_options :dependent => :destroy do |u|
		u.has_many :programmers
		u.has_many :outlets
		u.has_many :offers
		u.has_many :sub_channel_offers
	end
	
	# Include default devise modules. Others available are:
	# :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
				 :recoverable, :rememberable, :trackable, :validatable, :confirmable

	# Setup accessible (or protected) attributes for your model
	attr_accessible :email, :password, :password_confirmation, :remember_me, :phone, :title,
                  :first_name, :last_name, :admin, :address, :description, :avatar

	validates :first_name, :last_name, presence: true

	# Avatars
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
	
	def name
		self.first_name + " " + self.last_name
	end

	def count_offers
		offers.count + sub_channel_offers.count
	end #end offers_count method

	# Count all amount bids offers of outlets and amount offers of sub channel
	def count_amount_bids
		amount_offers = Offer.where('user_id = ?', self.id).sum('offers.yearly_offer')
		amount_sub_channel_offers = SubChannelOffer.where('user_id = ?', self.id).sum('sub_channel_offers.yearly_offer')
		amount_offers + amount_sub_channel_offers
	end #end count_amount_offer method

  def admin?
    self.admin
  end

  def self.category_for_highchart(name)
		User.order(:id).select(name).map { |x| x.send name  }
	end

	# Return array amount offer by user for highchart data
	def self.highchart_amount_offers
		User.order(:id).map{ |x| x.count_offers }
	end

	# Return array yearly offer by user for highchart data
	def self.highchart_amount_bids
		User.order(:id).map{ |x| x.count_amount_bids.round(2) }
	end
end

app/controllers/offers_controller.rb
# noinspection Rails3Deprecated
class OffersController < ApplicationController
	before_action :authenticate_user!
  before_action :sanitizeParameters, :only => [:create, :update]

	def new
	    @outlet = Outlet.find(params[:outlet_id])
	    @offer = Offer.new
	    @offer.outlet = @outlet
	    # @programmers = current_user.admin? ? @programmers = Programmer.all : Programmer.where(:user_id => current_user.id)
	    @programmers = Programmer.all
	end

	def index
    	@offers = Offer.all
	end

	def getDRTV
		list = []
		@offers = Offer.includes(:outlet)
		@offers.each do |offer|
			programmers = offer.programmers
			programmers.each do |prog|
				if prog.name == 'LifehacksDRTV'
					if offer.status == "Current"
						list.push([:offer => offer, :outlet_type => offer.outlet.outlet_type.name])
					end
				end
			end
		end
		respond_to do |format|
			format.json {
				render :json => list
			}
		end
	end

	def show
		@offer = Offer.find(params[:id])
    	@outlet = @offer.outlet
		@programmers = @offer.programmers
	end #end show action

	def edit
		@offer = Offer.find(params[:id])
		@outlet = Outlet.find(@offer.outlet.id)
    # @programmers = current_user.admin? ? @programmers = Programmer.all : Programmer.where(:user_id => current_user.id)

		@programmers = Programmer.all

		@url = params[:url]
    	@notes = @offer.notes
	end #end edit action

	def reassign
		@offer = Offer.find(params[:id])
		respond_to do |format|
			format.html {
				if request.post?
					if not User.find(params[:user][:id]).nil?
						@offer.user_id = params[:user][:id]
						if @offer.save
							redirect_to '/offers', :notice => 'Offer reassigned to ' + @offer.user.name
						else
							redirect_to '/offers/' + @offer.id.to_s + '/reassign', :error => 'Could not save offer'
						end
					else 
						redirect_to '/offers/' + @offer.id.to_s + '/reassign', :error => 'No such user exists'
					end
				end
			}
		end
	end

	def update
		@offer = Offer.find(params[:id])
    @outlet = Outlet.find(@offer.outlet.id)
    respond_to do |format|
      format.html {
        if @offer.update_attributes(params[:offer])
          redirect_to :back, :notice => 'Offer updated successfully'
        else
					redirect_to :back, flash[:alert] = @offer.errors
        end
      }
    end
  end

	def create
		@offer = Offer.new(params[:offer])
		@outlet = @offer.outlet
		@offer.user = current_user
		respond_to do |format|
			if @offer.save
				format.html { redirect_to edit_offer_path(@offer.id), notice: 'Offer was created successfully' }
			else
				format.html { redirect_to :back, flash[:alert] = @offer.errors }
			end
		end
	end

	def destroy
		@offer = Offer.find(params[:id])
		@offer.destroy

		respond_to do |format|
		  if @offer.destroy
			  format.html { redirect_to :back, :notice => 'Offer deleted successfully.' }
			else
				format.html { redirect_to :back, :error => 'Offer could not be deleted.' }
			end
		end
	end #end destroy action

	def preview
    @offer = Offer.find(params[:id])
    @outlet = @offer.outlet
  end

  def sendWorksheet
    @offer = Offer.find(params[:id])
    toEmail = params[:toEmail]
    carbonCopy = params[:carbonCopy]
    subject = params[:subject]
    emailMessage = params[:emailMessage]

    @error = false
    if toEmail == '' || !toEmail.include?('@') || toEmail.length < 4
			@error = 'Destination email address was not valid.'
    elsif subject == ''
      @error = 'Email subject line was blank.'
    else
      if params[:offer] && params[:offer][:attachment]
        @email = WorksheetMailer.sendWorksheet(@offer, toEmail, carbonCopy, subject, emailMessage, params[:offer][:attachment]).deliver
      else
        @email = WorksheetMailer.sendWorksheet(@offer, toEmail, carbonCopy, subject, emailMessage, nil).deliver
      end
    end
  end

	def setClosedWon
		@offer = Offer.find(params[:id])
		@offer.status = 'Closed Won'
		respond_to do |format|
			if @offer.save
				format.html {
					redirect_to :back, :notice => 'Offer status updated successfully.'
				}
      else
        format.html {
          redirect_to :back, :error => 'Error: offer could not be updated.'
        }
      end
		end
	end

	def setClosedLost
		@offer = Offer.find(params[:id])
		@offer.status = 'Closed Lost'
		respond_to do |format|
			if @offer.save
				format.html {
					redirect_to :back, :notice => 'Offer status updated successfully.'
				}
      else
        format.html {
          redirect_to :back, :error => 'Error: offer could not be updated.'
        }
			end
		end
	end
end

app/helpers/offers_helper.rb
module OffersHelper
	
	def day_arr
		["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]
	end

  def constituteDayparts(cells)
    # Strip trailing comma if there is one
    cells = cells[0, cells.length - 1] unless cells.last != ','
    # Split individual cells
    cells = cells.split(',')
    # For each cell...
    cells.each do |cell|
      day, time = cell.split('-')
    end
  end
end

app/views/offers/_form.html.erb
<%= form_for @offer do |f| -%>
    <%= f.hidden_field :time_cells, :value => @offer.time_cells %>
    <%= f.hidden_field :total_hours %>
    <%= f.hidden_field :outlet_id, :value => @offer.outlet.id %>
    <%= f.hidden_field :mvpdSubscriberRate, :id => 'mvpdSubscriberRate' %>
    <%= f.hidden_field :mvpdOtaSubRate, :id => 'mvpdOTASubRate' %>
    <%= f.hidden_field :halfHourRate, :id => 'halfHourRate' %>
    <%= f.hidden_field :runningAudienceTotal, :id => 'runningAudienceTotal' %>
    <%= f.hidden_field :runningHoursTotal, :id => 'runningHoursTotal' %>
    <%= f.hidden_field :runningWeeklyRateTotal, :id => 'runningWeeklyRateTotal' %>

    <% %w(morning daytime eveningNews localPrimeTime nationalPrimeTime lateNews lateNight overnights).each do |daypart| -%>
        <% %w(Audience Rate Hours WeeklyRate).each do |item| -%>
            <% id = [daypart, item].join %>
            <% name = "offer[#{id}]" %>
            <input type="hidden" name="<%= name %>" id="<%= id %>"/>
        <% end %>
    <% end %>
    <div class="row">
      <div class="col-md-6">
        <h1><%= @outlet.name %></h1>
        <p><a href="<%= url_for(edit_outlet_path(@outlet.id)) %>">
          <button type="button" class="btn btn-default">Edit Outlet</button>
        </a></p>
        <div class="form-group">
          <%= fields_for @offer.outlet do |o| -%>
              <%= o.label :subs, 'MVPD Subscribers' %>
              <%= o.text_field :subs, :class => 'form-control delimited', :id => 'mvpdSubscribers' %>
              <%= o.label :over_air, 'OTA Homes' %>
              <%= o.text_field :over_air, :class => 'form-control delimited', :id => 'otaHomes' %>
              <%= o.label :total_homes, 'Total Homes' %>
              <%= o.text_field :total_homes, :class => 'form-control delimited', :id => 'totalHomes' %>
          <% end %>
        </div>
        <div style="margin-bottom:15px;">
          <a href="#">
            <button type="button" class="btn btn-primary" id="selectAll">Select All</button>
          </a>
          <a href="#">
            <button type="button" class="btn btn-primary" id="invert">Invert Selection</button>
          </a>
          <a href="#">
            <button type="button" class="btn btn-primary" id="clear">Clear</button>
          </a>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <h3><strong>Potential #:</strong> <%= @outlet.id.to_s %></h3>
          <h3><strong><%= f.label :dma, 'DMA:' %></strong> <%= @outlet.dma.name rescue 'None' %></h3>
          <h3><strong><%= f.label :subs, 'Subs:' %></strong> <%= number_with_delimiter @outlet.subs %></h3>

          <label class="sr-only" for="exampleInputAmount">Amount (in dollars)</label>
          <div class="form-group">
            <%= f.text_field :dollar_amount, :class => 'form-control', :placeholder => @offer.dollar_amount, :style => 'width: 30%;', :id => '247mvpdSubEstimate' %>
          </div>
        </div>
        <% if action_name != 'new' -%>
          <div class="form-group">
            <a href="<%= url_for(offer_path(@offer.id)) %>">
              <button type="button" class="btn btn-default">Go to Show View</button>
            </a>
            <a href="<%= url_for(offer_path(@offer.id)) + '/preview' %>">
              <button type="button" class="btn btn-default"><i class="fa fa-envelope"></i> Send via Email</button>
            </a>
            <a href="#">
              <button type="button" class="btn btn-default" id="copyLinkButton" data-url="<%= offer_url(@offer.id) %>">
                <i class="fa fa-link"></i> Copy Offer Link
              </button>
            </a>
          </div>
          <% if @offer.zoho_exported %>
            <div class="form-group">
              <button type="button" class="btn btn-danger" disabled>Exported to Zoho</button>
            </div>
          <% else %>
            <div class="form-group">
              <a href="<%= url_for(zoho_export_potential_path) + '?id=' + @offer.id.to_s %>">
                <button type="button" class="btn btn-danger">Export to Zoho Potentials
                  <i class="fa fa-arrow-up" aria-hidden="true"></i></button>
              </a>
            </div>
          <% end %>
        <% end %>
      </div>
    </div> <!-- end row -->

    <div class="row">
      <div class="col-md-8 hours_div">
        <div class="gridContainer">
          <div class="gridContainerHeader" style="display:flex;">
            <%= render :partial => 'offers/grid' %>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="rate_info">
          <h1>Rate</h1>
          <p>Hourly Rate: <%= f.text_field :hourly_rate, :id => 'hourlyRate', :class => 'form-control' %></p>
          <p>Total
            Hours: <%= f.text_field :total_hours, :value => @offer.total_hours, :id => 'totalHours', :class => 'form-control' %></p>
          <table class="table table-condensed">
            <thead>
            <tr>
              <td>Offer</td>
              <td>Hours</td>
              <td>
                <div class="pull-right">Rate</div>
              </td>
            </tr>
            </thead>
            <tbody>
            <tr>
              <td>Weekly</td>
              <td>
                <%= f.text_field :weekly_hours, :value => @offer.weekly_hours, :id => 'weeklyHours', :class => 'form-control input-sm' %>
              </td>
              <td>
                <%= f.text_field :weekly_offer, :class => 'form-control input-sm ', :id => 'weeklyRate' %>
            </tr>
            <tr>
              <td>Monthy</td>
              <td>
                <%= f.text_field :monthly_hours, :value => @offer.monthly_hours, :id => 'monthlyHours', :class => 'form-control input-sm ' %>
              </td>
              <td>
                <%= f.text_field :monthly_offer, :id => 'monthlyRate', :class => 'form-control input-sm' %>
              </td>
            </tr>
            <tr>
              <td>Yearly</td>
              <td>
                <%= f.text_field :yearly_hours, :value => @offer.yearly_hours, :id => 'yearlyHours', :class => 'form-control input-sm ' %>
              </td>
              <td>
                <%= f.text_field :yearly_offer, :class => 'form-control input-sm ', :id => 'yearlyRate' %>
              </td>
            </tr>
            </tbody>
          </table>
          <div>
            <button type="button" id="calculate" class="btn btn-primary">Calculate</button>
            <button type="button" id="reset" class="btn btn-default">Reset</button>
          </div>
        </div>
        <br/>
        <div>
          <h2>Potential Block Programmer</h2>
          <% if @programmers.nil? || @programmers.empty? %>
              You must create a programmer record to associate with this offer before you can save it.
          <% else %>
              <%= select('offer', 'programmer_ids', @programmers.order(:name).collect { |p| [p.name, p.id] }, {include_blank: true}) %>
          <% end %>
          <p>&nbsp;</p>
          <p><%= link_to 'Add a Block Programmer', new_programmer_url, :class => 'btn btn-default' %></p>
        </div>
        <div>
          <p><strong>Programming</strong></p>
          <%= f.text_field :programming, :class => 'form-control' %>
        </div><br />
        <div>
          <p><strong>Available Date</strong></p>
          <%= f.text_field :available_date, :class => 'form-control dp' %>
        </div>
        <br/>
        <div>
          <h1>Notes</h1>
          <textarea class="form-control offer_note" name="offer[internalNotes]" id="offer_internalNotes"><%= @offer.internalNotes %></textarea>
          <br />
          <% if current_user.admin? %>
              <h1>Admin Options</h1>
              <p>Add a note to the Gross Rate Worksheet</p>
              <textarea class="form-control offer_note" rows="7" name="offer[grNotes]" id="offer_grNotes"><%= @offer.grNotes %></textarea>
          <% else %>
              <%= f.hidden_field :grNotes %>
          <% end %>
          <% if current_user.admin? %>
              <br/>
              <p>Add a note after the Dayparts dialog</p>
              <textarea class="form-control offer_note" name="offer[dpNotes]" rows="5" id="offer_dpNotes"><%= @offer.dpNotes %></textarea>

          <% else %>
              <%= f.hidden_field :dpNotes %>
          <% end %>

          <% if current_user.admin? %>
          <br/>
              <p>Add a disclaimer after the Programming Schedule</p>
              <textarea class="form-control offer_note" rows="7" name="offer[disclaimer]" id="offer_disclaimer"><%= @offer.disclaimer %></textarea>
          <% else %>
              <%= f.hidden_field :disclaimer %>
          <% end %>
        </div>
        <br/>
        <div>
          <%= f.submit 'Save Offer', :class => 'btn btn-success btn-lg' %>
        </div>
      </div>
    </div>
<% end %>

app/views/offers/_offer.html.erb
<% unless offer.programmers.empty? %>
	<tr>
		<td>
			<% offer.programmers.each do |programmer| %>
				<%= programmer.name %><br/>
			<% end %>
		</td>
		<td>
			<%= number_to_currency offer.dollar_amount %>
		</td>
		<td>
			<%= offer.updated_at.strftime("%m/%d/%Y") %>
		</td>

		<td>
			<%= link_to "edit", edit_outlet_offer_path(offer.outlet, offer) %> |
			<%= link_to "delete", [offer.outlet, offer], :confirm => "Are you sure?", :method => :delete %>
		</td>
	</tr>
<% else %>
	<div class="offer_field">
		"You not have any programmer"
	</div>
<% end %>

app/views/offers/edit.html.erb
<%= stylesheet_link_tag 'offers' %>
<%= render :partial => 'offers/form' %>

app/views/offers/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="page-title">
      <% if current_user.admin? %>
        <h1>All Potentials</h1>
        <ol class="breadcrumb">
          <li><a href="#"><i class="fa fa-home"></i></a></li>
          <li class="active">All Potentials</li>
        </ol>
      <% else %>
        <h1>My Potentials</h1>
        <ol class="breadcrumb">
          <li><a href='#'><i class="fa fa-home"></i></a></li>
          <li class="active">My Potentials</li>
        </ol>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <div class="navButtons">
      <%= button_to 'New Media Outlet', new_outlet_path, {:class => 'btn btn-primary', :method => :get} %>
      <%= button_to 'New Programmer', new_programmer_path, {:class => 'btn', :method => :get} %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="filterBox">
        <input type="text" class="form-control input-md filterText" placeholder="Filter" type="search">
        <select id="filterByColumn" style="margin-top: 5px;">
          <option value="all">All</option>
          <option value="current">Active</option>
          <option value="closedWon">Closed Won</option>
          <option value="closedLost">Closed Lost</option>
        </select>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <canvas id="pieChart" height="200" width="200"></canvas>
  </div>
  <div class="col-md-6"></div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default margin-b-30">
      <div class="panel-heading">
        <h4 class="panel-title">Offers</h4>
        <!--<div class="panel-actions">-->
          <!--<a href="#" class="panel-action panel-action-toggle" data-panel-toggle></a>-->
          <!--<a href="#" class="panel-action panel-action-dismiss" data-panel-dismiss></a>-->
        <!--</div>-->
      </div>
      <div class="panel-body">
        <div class="table-responsive">
          <table id="basic-datatables" class="table table-striped sortable filterable">
            <thead>
              <tr>
                <th>Created</th>
                <th>Company Name</th>
                <th>Offer Amount</th>
                <th>Gross Yearly Rate</th>
                <th>Outlet</th>
                <th>Subscribers</th>
                <th>OTA Homes</th>
                <th>Market</th>
                <th>Type</th>
                <th>Hours</th>
                <th>Status</th>
                <th>User</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @offers.each do |offer| %>
                <tr>
                  <td><%= offer.created_at.strftime '%m/%d/%Y' %></td>
                  <td>
                      <% offer.programmers.each do |p| %>
                      <%= p.name %>
                    <% end %>
                  </td>
                  <td><%= number_to_currency offer.dollar_amount %></td>
                  <td><%= number_to_currency offer.yearly_offer %></td>
                  <td><%= offer.outlet.name %></td>
                  <td><%= number_with_delimiter offer.outlet.subs %></td>
                  <td><%= number_with_delimiter offer.outlet.over_air %></td>
                  <td><%= offer.outlet.dma.name %></td>
                  <td><%= offer.outlet.outlet_type.name %></td>
                  <td><%= offer.total_hours %></td>
                  <% if offer.status == 'Current'
                     cls = 'current'
                   end
                    if offer.status == 'Closed Won'
                     cls = 'closedWon'
                   end
                    if offer.status == 'Closed Lost'
                       cls = 'closedLost'
                    end%>
                  <td class="<%= cls %>"><%= 


                  offer.status %>
                    
                  </td>
                  <td><%= offer.user.first_name rescue '' %></td>
                  <td>
                    <div class="btn-group">
                      <button type="button" class="btn btn-primary droptown-toggle" data-toggle="dropdown">
                        Actions&nbsp;<span class="caret"></span></button>
                      <ul class="dropdown-menu">
                        <li><a href="<%= url_for offer_path(offer.id) %>">Display</a></li>
                        <li><a href="<%= url_for edit_offer_path(offer.id) %>">Edit</a></li>
                        <li><a href="<%= url_for offer_path(offer.id) %>/preview">Preview Email</a></li>
                        <% unless offer.zoho_exported %>
                            <li><%= link_to 'Export to Zoho', zoho_export_potential_path + '?id=' + offer.id.to_s, :data => {:confirm => 'Are you sure you want to export this offer to Zoho?'} %></li>
                        <% end %>
                        <li><%= link_to 'Closed Won', offer_path(offer.id) + '/setClosedWon', :method => :post, :data => {:confirm => 'Are you sure?'} %></li>
                        <li><%= link_to 'Closed Lost', offer_path(offer.id) + '/setClosedLost', :method => :post, :data => {:confirm => 'Are you sure?'} %></li>
                        <li><%= link_to 'Reassign', offer_path(offer.id) + '/reassign' %></li>
                        <li><%= link_to 'Delete', offer_path(offer.id), :method => :delete, :data => {:confirm => 'Are you sure?'} %></li>
                      </ul>
                    </div>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/offers/new.html.erb
<%= stylesheet_link_tag 'offers' %>
<%= render :partial => 'offers/form' %>

app/views/offers/print.html.erb
<%= stylesheet_link_tag 'application', media: "all" %>
<%= stylesheet_link_tag 'offers', media: "all" %>
<%= stylesheet_link_tag 'style', media: "all" %>
<%= render :partial => 'offers/sheet' %>
<%= javascript_include_tag 'application' %>
  <% if controller_name == 'offers' -%>
      <%= javascript_include_tag 'offers' %>
  <% end %>
    <%= javascript_include_tag 'custom' %>

app/views/offers/show.html.erb
<div class="row">
  <div class="col-md-12">
    <%= render :partial => 'offers/sheet' %>
  </div>
</div>