config/routes.rb
Grid168::Application.routes.draw do

  get 'zoho/getContacts' => 'zoho#getContacts'

	resources :outlets do
		resources :offers
	end

	resources :offers do
		resources :notes
	end

	resources :programmers

	devise_for :users

  resources :users

	root :to => 'offers#index'

	get 'offers/:id/preview' => 'offers#preview'

  post 'offers/:id/sendWorksheet' => 'offers#sendWorksheet'

  post 'offers/:id/setClosedWon' => 'offers#setClosedWon'

  post 'offers/:id/setClosedLost' => 'offers#setClosedLost'

  get 'zoho/export_potential' => 'zoho#export_potential'

  get '/getDRTV' => 'offers#getDRTV'

  get '/offers/:id/reassign' => 'offers#reassign'
  post '/offers/:id/reassign' => 'offers#reassign'

  %w( 404 422 500 ).each do |code|
    get code, :to => 'errors#show', :code => code
  end

end

app/views/layouts/_footer.html.erb
 <footer>
  <div class="container text-center">
    &copy; Copyright <%= Time.now.year %> Across Platforms Inc. All rights reserved.
  </div>
</footer>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-inverse yamm navbar-static-top ">
            <div class="container">

                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                  <a class="navbar-brand" href="#">Grid168
                    <% if current_user.admin? %> Admin
                    <% end %></a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right navbar-top-drops">
                        <li class="dropdown profile-dropdown">
                            <a href="#" class="dropdown-toggle button-wave" data-toggle="dropdown" role="button" >
                                <%= current_user.first_name %> <%= current_user.last_name %>&nbsp;&nbsp;<i class="fa fa-bars"></i></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <%= link_to edit_user_registration_path do -%>
                                        <i class="fa fa-user"></i>&nbsp;My Account
                                    <% end %>
                                </li>
                                <li>
                                    <%= link_to destroy_user_session_path, :method => :delete do -%>
                                        <i class="fa fa-key"></i>&nbsp;Log Out
                                    <% end %>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div><!--/.container-fluid -->
        </nav>

app/views/layouts/_notis.html.erb
<% flash.each do |key, value| -%>
    <div id="message" class="flash">
      <div class="flash flash-padding">
        <div id="inner-message" class="alert <%= key == 'alert' ? "alert-danger" : "alert-success" %> flash">
          <button type="button" class="close flash" data-dismiss="alert">&times;</button>
          <script type="text/javascript">
            console.log("Notification => {:key => [<%= key %>], :message => [<%= value %>]}");
          </script>
          <div class="alert-text"><i class="fa fa-exclamation-circle"></i>&nbsp;<%= value %></div>
        </div>
      </div>
    </div>
<% end %>

app/views/layouts/_submenu.html.erb
 <nav class="navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-main" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div id="navbar-main" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <% if current_user.admin? -%>
                            <%= controller_name == 'offers' ? raw("<li class='active'>") : raw("<li>") %>
                            <a href="<%= url_for(offers_url) %>">All Potentials </a></li>
                        <% else %>
                            <li><a href="<%= url_for(offers_url) %>">My Potentials</a></li>
                        <% end %>

                        <%= controller_name == 'outlets' ? raw("<li class='dropdown active'>") : raw("<li class='dropdown'>") %>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Media Outlets<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="<%= url_for(outlets_url) %>">All Media Outlets</a></li>
                                <li><a href="<%= url_for(new_outlet_url) %>">New Media Outlet</a></li>
                            </ul>
                        </li>

                        <%= controller_name == 'programmers' ? raw("<li class='dropdown active'>") : raw("<li class='dropdown'>") %>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Programmers <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="<%= url_for(programmers_url) %>">View Programmers</a></li>
                                <li><a href="<%= url_for(new_programmer_url) %>">New Programmer</a></li>
                            </ul>
                        </li>
                        <% if current_user.admin? %>
                            <%= controller_name == 'users' ? raw("<li class='dropdown active'>") : raw("<li class='dropdown'>") %>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Users <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<%= url_for(users_url) %>">Manage Users</a></li>
                                </ul>
                            </li>
                        <% end %>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">

<!--                         <li>
                            <form class="mainnav-form" role="search">
                                <input type="text" class="form-control input-md" placeholder="Search">
                                <button class="btn btn-sm mainnav-form-btn" type="button"><i class="fa fa-search"></i></button>
                            </form>
                        </li> -->
                    </ul>
                </div><!--/.nav-collapse -->
            </div><!--/.container-fluid -->
        </nav>

app/views/layouts/_zoho_contact_search.erb
<div class="row">
  <div class="panel panel-default margin-b-30">
    <div class="panel-heading">
      <h4 class="panel-title">Import from Zoho</h4>
    </div>
    <div class="panel-body">
      <div class="col-sm-3">
        <%= form_tag zoho_getContacts_url, {:remote => true, :class => 'form-horizontal'} %>
          <div class="form-group">
            <div class="col-lg-12"><%= text_field_tag 'zohoSearchTerm', nil, {:class => 'form-control', :placeholder => 'Search terms...' }%></div>
          </div>

          <div class="form-group">
            <div class="col-lg-12">Search by
              <select name="zohoSearchBy" id="zohoSearchBy" style="width: 100%;">
                <option value="email">Email</option>
                <option value="company">Company</option>
                <option value="last_name">Last Name</option>
                <option value="first_name">First Name</option>
              </select>
            </div>
          </div>
        <button type="button" class="btn btn-default" style="float: right;" id="zohoSearch">Search <i class="fa fa-search"></i></button>
      </div>
      <div id="zohoContactsContainer" class="col-sm-9"></div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
	<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UI-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	  <title>Grid168</title>
    <%= stylesheet_link_tag 'application' %>
    <%= stylesheet_link_tag 'waves.min' %>
    <%= stylesheet_link_tag 'menu' %>
    <%= stylesheet_link_tag 'style' %>
    <%= stylesheet_link_tag 'notis' %>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <%= favicon_link_tag %>
	  <%= csrf_meta_tags %>
	</head>
  <body data-controller="<%= controller_name %>" data-action="<%= action_name %>" data-development="<%= Rails.env.development? %>">
    <% if signed_in? %>
        <%= render :partial => 'layouts/menu' %>
        <div class="clearfix"></div>
        <%= render :partial => 'layouts/submenu' %>
        <div class="container page-wrapper">
          <%= yield %>
        </div>
    <% else %>
      <%= yield %>
      <%= render :partial => 'layouts/footer' %>
    <% end %>
    <%= render :partial => 'layouts/notis' %>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.bundle.min.js"></script>
    <%= javascript_include_tag 'application' %>
  </body>
</html>